### ISSUE TITLE
mismatch of props

### ISSUE THREAD

**Issue by rwparrish** [learn-co-curriculum/react-hooks-react-router-nested-routes#4]
### Canvas Link

Not available yet

### Concern

When updating the code in `Home.js` and `UserCard.js` to make use of passing data via context, the destructuring done by the updated `UserCard.js` component changes to `id` and `name`. This causes the code to break because the props being passed `UserCard.js` from `Home.js` do not change from `key` and `user`.

**Comment by lizbur10** [comment]
Hey @rwparrish ! Thanks for catching this! It should now be fixed 💙
